### PR TITLE
Lll experiemntal

### PR DESCRIPTION
**Pull request by MrDuartePT**
@Petingoso
I think it work but i dont have time to test the other profile. 
Tomorrow i rebase the two commit in to one. 
If work on your machine as well merge it.

### CODE REVIEW

**Comment by MrDuartePT** [comment]
For everyone else
This will add base to merge with @jonhfanv2 LLL project https://github.com/johnfanv2/LenovoLegionLinux/tree/main

**Comment by MrDuartePT** [comment]
this syntax in fact dosent work:
```
name: balanced-bat
entries:
  - fan1_speed: [0, 0, 0, 1000, 1200, 1600, 1800, 2600, 3000, 0]
    fan2_speed: [0, 0, 0, 1000, 1200, 1600, 1800, 2600, 3000, 0]
    cpu_lower_temp: [0, 50, 55, 60, 65, 70, 78, 83, 88, 0]
    cpu_upper_temp: [50, 55, 60, 65, 70, 78, 83, 88, 127, 0]
    gpu_lower_temp: [0, 50, 55, 60, 65, 70, 78, 83, 88, 0]
    gpu_upper_temp: [50, 55, 60, 65, 70, 78, 83, 88, 127, 0]
    ic_lower_temp: [0, 30, 40, 50, 55, 127, 127, 127, 127, 0]
    ic_upper_temp: [30, 40, 50, 55, 127, 127, 127, 127, 127, 0]
    acceleration: [3, 3, 3, 3, 3, 3, 2, 2, 1, 1]
    deceleration: [3, 3, 3, 3, 3, 3, 2, 2, 1, 1]
enable_minifancurve: false
```
output terminal:
```
➜  legion-fan-utils-linux git:(LLL-experiemntal) doas ./service/fancurve-set.sh            
Applying Balance Mode Profile   -> battery...
Successfully wrote preset /etc/lenovo-fan-control/profiles/balanced-bat to hardware
➜  legion-fan-utils-linux git:(LLL-experiemntal) doas cat /sys/kernel/debug/legion/fancurve
EC Chip ID: 8227
EC Chip Version: 2a4
legion_laptop features: fancurve powermode platformprofile platformprofilenotify minifancurve
legion_laptop ec_readonly: 0
ACPI CFG error: 0
ACPI CFG: 2081289482
temperature access method: 1
CPU temperature error: 0
CPU temperature: 45
CPU temperature EC error: 0
CPU temperature EC: 45
CPU temperature ACPI error: 0
CPU temperature ACPI: 45
CPU temperature WMI error: 0
CPU temperature WMI: 0
CPU temperature WMI2 error: 0
CPU temperature WMI2: 45
GPU temperature error: 0
GPU temperature: 0
GPU temperature EC error: 0
GPU temperature EC: 0
GPU temperature ACPI error: 0
GPU temperature ACPI: 0
GPU temperature WMI error: 0
GPU temperature WMI: 0
GPU temperature WMI2 error: 0
GPU temperature WMI2: 0
fan speed access method: 1
1 fanspeed error: 0
1 fanspeed: 1777
1 fanspeed EC error: 0
1 fanspeed EC: 1777
1 fanspeed ACPI error: 0
1 fanspeed ACPI: 1700
1 fanspeed WMI error: 0
1 fanspeed WMI: 0
1 fanspeed WMI2 error: 0
1 fanspeed WMI2: 1700
2 fanspeed error: 0
2 fanspeed: 1937
2 fanspeed EC error: 0
2 fanspeed EC: 1937
2 fanspeed ACPI error: 0
2 fanspeed ACPI: 1900
2 fanspeed WMI error: 0
2 fanspeed WMI: 0
2 fanspeed WMI2 error: 0
2 fanspeed WMI2: 1900
powermode access method: 3
powermode error: 0
powermode: 2
powermode EC error: 0
powermode EC: 0
powermode ACPI error: -5
powermode ACPI: 0
powermode WMI error: 0
powermode WMI: 2
has custom powermode: 1
ACPI rapidcharge error: 0
ACPI rapidcharge: 0
WMI backlight 2 state: 0
WMI backlight 3 state: 0
WMI light IO port: 0
WMI light y logo/lid: 0
EC minifancurve feature enabled: 1
EC minifancurve on cool: true
EC lockfancontroller error: 0
EC lockfancontroller: false
EC fanfullspeed error: false
EC fanfullspeed status: 0
EC fan curve current point id: 1
EC fan curve points size: 9
Current fan curve in hardware (embedded controller):
rpm1|rpm2|acceleration|deceleration|cpu_min_temp|cpu_max_temp|gpu_min_temp|gpu_max_temp|ic_min_temp|ic_max_temp
0        0       2       2       0       48      0       60      0       41
1700     1900    2       2       45      54      56      60      39      44
1900     2000    2       2       51      58      56      60      42      50
2200     2100    2       2       55      62      56      60      46      127
2300     2400    2       2       59      71      56      60      127     127
2600     2700    2       2       68      76      56      65      127     127
2900     3000    2       2       72      81      61      69      127     127
3500     3500    2       2       78      90      66      77      127     127
3800     3800    2       2       87      127     72      127     127     127
=====================
➜  legion-fan-utils-linux git:(LLL-experiemntal) legion_cli minifancurve-status
True
```

**Comment by Petingoso** [comment]
too bad it doesn't work, when you're finished with everything I'll merge

**Comment by MrDuartePT** [comment]
Evrtging work besides the minifancurve try to see why. 
Tryit on your system
Besides the MINICURVE=0 the command run but the minicurve dosent get disable
See the comment i put in the lines

**Comment by MrDuartePT** [comment]
I fix the service the only thing i have to debug is why the minifancurve dosent work

**Comment by MrDuartePT** [comment]
Now everything work is good to be merge

**Pull request merged**
